---
title: "R Training 2"
author: "Rachel Kenny"
date: "4/01/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R code notes
+ Capitalization matters in r code. Lowercase and uppercase are recognized as different characters
+ To refer to a column in a dataframe, you can use a [$] symbol between the name of the dataframe and the name of the column


### Loading packages & data
```{r load}

# Load packages
library(readxl)
library(tidyverse)
library(janitor)

# Load agua chinon veg data
ac_data_raw <- read_excel("OCWR_AC_2019_Data.xlsx")
ac_data <- clean_names(ac_data_raw)

# Load weir oak restoration data
oak_data_raw <- read_csv("Weir_Oak_Restoration_Data_winter19.csv")
oak_data <- oak_data_raw %>% 
  clean_names()



```


### Data wrangling 1
```{r wrangle1}

ac_data2 <- ac_data %>% 
  select(polygon_id, transect)

# To refer to a column in a dataframe, you can use a [$] symbol
oak_data$height_cm
View(oak_data$height_cm)

View(oak_data)

# Another way to refer to a column is by referring to the number of the column using square brackets []. Using a colon indicates subsequent columns. For example [4:6] means columns 4 through 6. Using a negative means everthing except for that column.
oak_data[4]
oak_data[4:6]
oak_data[-4]

# Use the [which] code to refer to specific observations in the code. In this example, we are replacing the words "5M Buffer" in the polygon ID column with the words "5M BUFFER" so that R will recognize these polygon IDs as being the same
ac_data$polygon_id[which(ac_data$polygon_id=="5M Buffer")] <- "5M BUFFER"


# There are a few ways to rename a column
# Method 1: use function [names] 
ac_data2 <- ac_data
names(ac_data2)[1] <- paste("habitat") # name column 1 "habitat"


# Method 2: use function [colnames] 
ac_data2 <- ac_data
colnames(ac_data2)[4:6] <- c("pin", "type_data", "code_species") # rename columns 4 through 6

View(ac_data2)


```


### Data wrangling 2
```{r wrangle2}

# There are a few ways to create a new column
# Method 1: Use the function [mutate]. Within the new column you can make transformations on your data.
oak_data2 <- oak_data %>% 
  mutate(new_column=height_cm*2)

# Method 2: Create a new column using the [$] symbol
oak_data3 <- oak_data
oak_data3$height_rounded <- round(oak_data3$height_cm)

View(oak_data2)
View(oak_data3)

```


### Creating tables
```{r tables}

# To count observations by group, use the [group_by] and [count] functions. Here are two examples below

# agua chinon data example - number of observations per species code in each polygon and transect
richness1 <- ac_data %>%
  group_by(polygon_id, transect) %>% 
  count(species_code)

View(richness1)

# oak data example - # of plantings watered or not watered by sampling group
oak_water_sampling_grp <- oak_data %>% 
  group_by(sampling_group) %>% 
  count(water_yes_no)

View(oak_water_sampling_grp)

View(oak_data)


```




